### ISSUE TITLE
Move Mail Shortcuts save problem

### ISSUE THREAD

**Issue by hopalongrock** [robert7k/moveMailShortcuts#1]
Move Mail Shortcuts doesn't remember account, automatically changes to the Folder in 1st account where the folder exists.
For example if I assign Folder 1 to Local Folders / Trash and save it, and go out of options and back, Folder 1 changes to 1st account / Trash.
If I assign Folder 1 to Local Folders / Sent and save it, and go out of options and back, Folder 1 changes to 3rd account / Sent - it's the 1st account where Sent exists.
If I assign for Folder 1 to Local Folders / Outbox and save it, it doesn't change, Outbox is only in Local Folders.

**Comment by robert7k** [comment]
Thanks for reporting. I can confirm this issue exists and will fix it

**Comment by robert7k** [comment]
I fixed this issue and submitted it to addons.thunderbird.net. Thunderbird should be able to update soon. Thanks again for reporting this issue.
