### ISSUE TITLE
Move does not work

### ISSUE THREAD

**Issue by KlausEyl** [robert7k/moveMailShortcuts#11]
TB 115.3.1 

I just installed Move Mail Shortcuts. I defined a target folder 
![image](https://github.com/robert7k/moveMailShortcuts/assets/133502571/9426cac4-5d14-408b-b3df-d4e287de3f0e)
and a key
![image](https://github.com/robert7k/moveMailShortcuts/assets/133502571/9315cb2e-0103-464b-807f-ed3c78436dec)
When I press the key while on a message (not opened), the message disappears but does not appear in the target folder.
I found this in the console, but I am not sure if this is related:
![image](https://github.com/robert7k/moveMailShortcuts/assets/133502571/6b6edad3-e96b-45c5-9fe7-3f4a51dbf4f9)

**Comment by robert7k** [comment]
Are you sure you don't have another folder with the same name, maybe in another account?

Can you find the lost message using the search?

**Comment by KlausEyl** [comment]
I checked, and there is no other folder. Also, I selected the correct account.

The search does not show the message; it is completely gone.

I can help with debugging.

**Comment by robert7k** [comment]
Does the error message you posted appear every time you try this?

**Comment by robert7k** [comment]
Closed due to inactivity.
