### ISSUE TITLE
Move broke after a thunderbird upgrade

### ISSUE THREAD

**Issue by wlauppe** [robert7k/moveMailShortcuts#14]
Hello, i use your excellent extension, but unfortunately it stopped working. 
I suspect it has something todo with the upgrade of the thunderbird package. 

Currently I'm running: ```Ubuntu Linux 22.04.5 LTS``` and when i run ```thunderbird --version``` it returns ```Thunderbird 115.15.0```

In the console log, when I press my move shortcut,  I find the following output: 

```
Received command move_mail_0. [background.js:14:10](moz-extension://64503860-9fc6-46cd-8a8f-6fac06bf1406/background.js)
Got saved folder value: {"folderPath":"/[Gmail]/archiv","accountId":"account1"} [background.js:21:10](moz-extension://64503860-9fc6-46cd-8a8f-6fac06bf1406/background.js)
Message IDs:
```
Message IDs: seems to be empty.  Is it supposed to be like this?
Do you have any ideas, what could be wrong and how to fix it? 

Thanks a lot for your help!

**Comment by robert7k** [comment]
Could it be that the update lead to the shortcuts now being used by Thunderbird itself?

Which shortcuts have you configured? Have you tried using other shortcuts?

**Comment by wlauppe** [comment]
Hello: 
i have configured 1 shortcut like this: 
![screenshot_20240930_101132](https://github.com/user-attachments/assets/d4de18f7-24de-4891-977f-835e8faca1d8)
and i think pressing the shortcut works, because I get the output on the console log, as mentioned above. So command ```move-mail_0``` is received. What i dont understand, is why there is nothing after ```Message IDs:```
shouldnt there be the message ids of the mails to be moved?

**Comment by robert7k** [comment]
I can't reproduce this problem on Thunderbird 115.15.0 on Linux.

Do you have any other add-ons installed?

**Comment by robert7k** [comment]
Do you have your preview pane hidden? If yes, this would be a duplicate of #10.

**Comment by wlauppe** [comment]
Hello Robert, thanks for pointing that out. I am not sure, i think i have the preview pane always on, so it might have been unrelated to that.  At the moment with Thunderbird Version 115.16.2 everything works fine on ubuntu linux
 (If the preview pane is not hidden) so im closing this.
