### ISSUE TITLE
Move multiple messages

### ISSUE THREAD

**Issue by robert7k** [robert7k/moveMailShortcuts#3]
When multiple messages are selected, all should be moved when the corresponding keyboard shortcut is pressed.

Handling multiple messages will only be available from Thunderbird 81 on (see https://thunderbird-webextensions.readthedocs.io/en/latest/changes/beta81.html). I'll leave this issue open to handle this as soon as TB 81 is out.

Split from #2.

**Comment by hi5** [comment]
Nice addon - I think it is already possible to move multiple messages as https://github.com/kewisch/quickmove-extension/ manages to do so - select several messages and then you can move them to a folder after searching/typing the name, but shortcuts as in your addon are faster for often used folders of course.

**Comment by robert7k** [comment]
Thanks for the hint, I'll have a look. :-)

**Comment by bege10** [comment]
> 
> 
> Thanks for the hint, I'll have a look. :-)

Did you find a way to accomplish this? It would be very helpful. Thanks.

**Comment by hi5** [comment]
Thanks :+1:

**Comment by bege10** [comment]
🙏
