### ISSUE TITLE
multiple subfolder hanging 

### ISSUE THREAD

**Issue by lhedrich** [robert7k/moveMailShortcuts#4]
Dear Robert,

thanks for that tool it saves me a lot of team. 
I had an issue with subfolder of subfolders. The tools hangs.
Downtracing it, it is the problem with the i variable on recursive entry of findSubfolder: 
background.js: 
line 81: 
" for (i = 0; i < list.length; i++)"
should be replaced by :
" for (let i = 0; i < list.length; i++)" 
then the tools is perfectly working for me on TB 78.3.1
I 'm not sure, if i can post that on the master branch. Hence the issue her. 
Thanks, Lars

**Comment by robert7k** [comment]
Hi Lars,
thanks for your report. Feel free to open a Pull Request. I'll fix it as soon as I find time otherwise.
Best regards,
Robert
