### ISSUE TITLE
Wish: just go to folders

### ISSUE THREAD

**Issue by hi5** [robert7k/moveMailShortcuts#5]
Say you have setup <kbd>Alt</kbd>+<kbd>1</kbd> as shortcut to folder "project1".
I would find it useful if I could press say, <kbd>Ctrl</kbd><kbd>Alt</kbd>+<kbd>1</kbd> to just GO TO folder "project1"

That way after I moved all messages to the correct folders, I can go to a folder quickly.

I'm guessing as you have to "move" part already done, just "go to" might something that might be feasible?

**Comment by robert7k** [comment]
Thanks for the suggestion, I added this feature for version 5 of this extension.

**Comment by hi5** [comment]
Works for me, thanks!
