### ISSUE TITLE
folder1 Alt-C shortcut doesn't work

### ISSUE THREAD

**Issue by hopalongrock** [robert7k/moveMailShortcuts#8]
I don't know whether Alt-C is used/reserved for other purpose, Alt-1 works fine.

Meanwhile I accidentally clicked on the delete button of folder1 and could not restore the folder1 line except by uninstalling and reinstalling the addon.
Is a simpler method exist?

**Comment by robert7k** [comment]
Alt+C works for me on Linux, so I guess it's reserved on other operating systems. As the shortcuts are managed by Thunderbird, and not the extension, there's nothing I can do about it.

What exactly do you mean by "could not restore the folder 1 line"? Did it disappear?
