### ISSUE TITLE
TB 102 Hotkey Alt 1 - Alt 5 is used for spaces toolbar

### ISSUE THREAD

**Issue by hopalongrock** [robert7k/moveMailShortcuts#9]
In TB 102 the hotkey Alt 1 - Alt 5 is used for spaces toolbar, and it seems they have priority over the addon keys.
Maybe you could assign other keys as default in the addon.
I only used Folder 1 (Alt 1), so I use now folder 6 (Alt 6).

**Comment by ErikLtz** [comment]
Also was very used to Alt+1 - now switched to Alt+X that appears free but would prefer to disable the Spaces menu on the left and free it's shortcuts Alt+1 to 5 for Move Mail Shortcuts instead...

**Comment by Dediggefedde** [comment]
TheIssue still exists and is pretty uncomfortable.

- Only 5 target folders remain
Especially sorting work-related messages requires more than 5 active folders.
- One-hand operation becomes pretty hard.
When sorting through lots of e-mails, I want to alternatingly click and press the shortkey, hence easy one-hand operation would pretty neat.

It would be awesome if we could just assign our own keybinds. 

Meanwhile I use an autohotkey script to map alt+[1-5] to alt[6-0] for better finger-access.
It also displays a 2s prompt on where the emails were moved to.

```ahk
#SingleInstance, force
SetTitleMatchMode, 2 
#IfWinActive Thunderbird
	
HideTrayTip() {
		TrayTip
}

!1::
	Send !6
	TrayTip, Thunderbird, Moved to Experiment, , 0
	SetTimer, HideTrayTip, -2000
	Return
!2::
	Send !7
	TrayTip, Thunderbird, Moved to Presentations, , 0
	SetTimer, HideTrayTip, -2000
	Return
!3::
	Send !8
	TrayTip, Thunderbird, Moved to Software, , 0
	SetTimer, HideTrayTip, -2000
	Return
!4::
	Send !9
	TrayTip, Thunderbird, Moved to Students, , 0
	SetTimer, HideTrayTip, -2000
	Return
!5::
	Send !0
	TrayTip, Thunderbird, Moved to Verwaltung, , 0
	SetTimer, HideTrayTip, -2000
	Return
```

**Comment by superkev73** [comment]
Yes, Thunderbird 115 takes over even more keyboard shortcuts, most of which I would never use. It would be great to have an option to override these so our own keep working. Maybe you can use something like this:

event.preventDefault();

to override the Thunderboard default keyboard shortcut if there is a conflict.

**Comment by robert7k** [comment]
> Maybe you can use something like this:
> 
> event.preventDefault();
> 
> to override the Thunderboard default keyboard shortcut if there is a conflict.

We don't receive DOM events where that could work. We only receive the command callback if the shortcut actually applies, so no simple way to intercept that.

There might be ways around, see also https://github.com/wshanks/tbkeys

Maybe you can use this extension to remove some of the shortcuts you would like to use.

**Comment by robert7k** [comment]
> In TB 102 the hotkey Alt 1 - Alt 5 is used for spaces toolbar, and it seems they have priority over the addon keys. Maybe you could assign other keys as default in the addon. I only used Folder 1 (Alt 1), so I use now folder 6 (Alt 6).

Thanks for reporting this, I updated the default keyboard shortcuts with de29c4aeb75b70bd85c6950e4c1bc6732facea94 (version 5 of this plugin) to use ALT+SHIFT+1 etc. to avoid the conflicts.
